CREATE OR REPLACE TABLE CIPEDW.DEMO (
	PLAYERID INTEGER NOT NULL,
	SITECODE VARCHAR(20) NOT NULL,
	RECORDACTIVEFLAG VARCHAR(1) NOT NULL,
	RECORDINSERTUSERID VARCHAR(80) NOT NULL,
	RECORDINSERTDATETIME TIMESTAMP NOT NULL,
	RECORDUPDATEUSERID VARCHAR(80) NOT NULL,
	RECORDUPDATEDATETIME TIMESTAMP NOT NULL,
	SOURCESYSTEMID INTEGER,
	JOBINSERTRUNID INTEGER,
	JOBUPDATERUNID INTEGER,
	CONSTRAINT PKDEMO PRIMARY KEY(PLAYERID, SITECODE)
);